apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: appbundle-project-dev
  source:
    path: argocd/apps-children/dev
    repoURL: https://github.com/cvora22/argocd-app-of-apps-parent.git
    targetRevision: HEAD