apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: appbundle-project-dev
  source:
    path: kustomized_helm/overlays/dev
    repoURL: https://github.com/cvora22/argocd-app-of-apps-child-guestbook.git
    targetRevision: HEAD
